### ISSUE TITLE
Aperture input region domain field is not saving for data input

### ISSUE THREAD

**Issue by splunk-voltron-github** [PaloAltoNetworks/SplunkforPaloAltoNetworks#80]
I'm seeing critical data input errors related to the _region_ field for data input. In creating the Aperture input type, it doesn't seem like the _region_ value is being saved, so when pushed to modinput execution, it's vacant and the input fails before it really starts.

Can you verify if the _region_ field is even saved?

```
2018-12-10 18:31:38,247 ERROR pid=18614 tid=MainThread file=base_modinput.py:log_error:307 | Get error when collecting events.
Traceback (most recent call last):
  File "/opt/splunk/etc/apps/Splunk_TA_paloalto/bin/splunk_ta_paloalto/modinput_wrapper/base_modinput.py", line 127, in stream_events
    self.collect_events(ew)
  File "/opt/splunk/etc/apps/Splunk_TA_paloalto/bin/aperture.py", line 64, in collect_events
    input_module.collect_events(self, ew)
  File "/opt/splunk/etc/apps/Splunk_TA_paloalto/bin/input_module_aperture.py", line 78, in collect_events
    url_domain = REGION_DOMAIN[region]
KeyError: None
```
inputs.conf:
```
[splunk@sv3-prdv-splkx-557:/opt/splunk/etc/apps/Splunk_TA_paloalto/local]$ pwd
/opt/splunk/etc/apps/Splunk_TA_paloalto/local
[splunk@sv3-prdv-splkx-557:/opt/splunk/etc/apps/Splunk_TA_paloalto/local]$ cat inputs.conf
[aperture://Aperture]
global_account = Aperture
index = sec_pan_aperture
interval = 60
[splunk@sv3-prdv-splkx-557:/opt/splunk/etc/apps/Splunk_TA_paloalto/local]$
```

Splunk Web UI for input:
![image](https://user-images.githubusercontent.com/14879051/49774630-2f1efd00-fcaa-11e8-840c-f2a2fb523564.png)

Here's the input config setup (edit in this case):
![image](https://user-images.githubusercontent.com/14879051/49774658-465dea80-fcaa-11e8-8adf-b1d636be0bd6.png)

**Comment by paulmnguyen** [comment]
This has been resolved in 6.1.1
